org: oxygenmiranda1
service: nodejs-aws-lambda
provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-3
  environment:
    MONGO_URI: ${env:MONGO_URI}
    ACCESS_TOKEN_SECRET: ${env:ACCESS_TOKEN_SECRET}
    REFRESH_TOKEN_SECRET: ${env:REFRESH_TOKEN_SECRET}
functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any