org: oxygenmiranda1
service: nodejs-aws-lambda
provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-3
  environment:
    MONGO_URI: ${env:MONGO_URI}
    ACCESS_TOKEN_SECRET: ${env:ACCESS_TOKEN_SECRET}
    REFRESH_TOKEN_SECRET: ${env:REFRESH_TOKEN_SECRET}
functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /api/login
          method: post
      - http:
          path: api/rooms
          method: get
          cors: true
      - http:
          path: api/rooms
          method: post
          cors: true
      - http:
          path: api/rooms/{id}
          method: get
          cors: true
      - http:
          path: api/rooms/{id}
          method: put
          cors: true
      - http:
          path: api/rooms/{id}
          method: delete
          cors: true
      - http:
          path: api/users
          method: get
          cors: true
      - http:
          path: api/users
          method: post
          cors: true
      - http:
          path: api/users/{id}
          method: get
          cors: true
      - http:
          path: api/users/{id}
          method: put
          cors: true
      - http:
          path: api/users/{id}
          method: delete
          cors: true
      - http:
          path: api/contacts
          method: get
          cors: true
      - http:
          path: api/contacts
          method: post
          cors: true
      - http:
          path: api/contacts/{id}
          method: get
          cors: true
      - http:
          path: api/contacts/{id}
          method: put
          cors: true
      - http:
          path: api/contacts/{id}
          method: delete
          cors: true
      - http:
          path: api/bookings
          method: get
          cors: true
      - http:
          path: api/bookings
          method: post
          cors: true
      - http:
          path: api/bookings/{id}
          method: get
          cors: true
      - http:
          path: api/bookings/{id}
          method: put
          cors: true
      - http:
          path: api/bookings/{id}
          method: delete
          cors: true
      - http:
          path: /{proxy+}
          method: any